server:
  port: 8081
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    api:
      path: /api/**
      url: http://127.0.0.1:8080/

security:
  oauth2:
    resource:
      jwt:
        key-value: 123
